#ifndef MIDI_STOMP_CONTROLLER_MIDISTOMPTYPES_H
#define MIDI_STOMP_CONTROLLER_MIDISTOMPTYPES_H

enum midiMode {NOTES, STEPS};
enum buttonState {UP, PRESSED, HELD, RELEASED};


#endif //MIDI_STOMP_CONTROLLER_MIDISTOMPTYPES_H
